### PR TITLE
DSECS full analysis

### PR DESCRIPTION
**Pull request by sebastian-sw**
Full working analysis, bug fixes, added _DSECS_steps. Output, in a list dicts, which contain original data used for analysis, current densities and fits separated for Alpha and Charlie.

### CODE REVIEW

**Comment by smithara** [comment]
Thanks! I'll keep an eye on this, though not sure if I will have time to deal with it until next week.

**Comment by sebastian-sw** [comment]
I added a notebook and edited the dsecs rst file in the docs to include the toolbox in the documentation so that in case we need to demonstrate a version somewhere, i can produce the documentation the documentation locally . I'm not sure how these actually should be added.

**Comment by smithara** [comment]
Cool! I checked the new process with datatree usage. This is a great start and I think we can refine it from here. Am I okay to take this PR from here now? (I will fix the format complaint and squash and merge this)

I'll make some further adjustments  (e.g. to documentation) in a follow-up PR. We should discuss these but I'm thinking about:
- change module name from `secs` to `dsecs`
- separate into two processes: `Preprocess` (adds in the apex coordinates, magnetic residuals; could perform some input validation), and `Analysis`
- store the outputs in the datatree under a branch, i.e. `data["DSECS_output"][0], data["DSECS_output"][1], ...`
  - naming it "DSECS_output" to distinguish it from outputs which could be made by some other process
  - I think making it hierarchical will be more organised. One could, for example, define a visualisation function that takes the whole `data["DSECS_output"]` branch as its input
- drop the `data.swarmpal.apply(process)` method in favour of simply `process(data)`

**Comment by sebastian-sw** [comment]
That sounds good! you're okay to take the PR.

**Pull request merged**
